project:
  type: website
  output-dir: docs

website:
  title: "DS4I Assignment 2"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - ds4i_assignment2.qmd
      - code_appendix.qmd
      - plaigarism_declaration.qmd

format:
  html:
    embed-resources: true
    theme: lux
    css: styles.css
    toc: true
    max-width: 50em

execute:
  cache: true
  echo: false

bibliography: references.bib